# Generated by Django 4.2.28 on 2026-02-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=300)),
                ('mouth_size', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('current_quantity', models.IntegerField()),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier')),
            ],
        ),
    ]
